### ISSUE TITLE
Github Pages for docs?

### ISSUE THREAD

**Issue by Bobingstern** [UnsignedArduino/TkZero#1]
You may want to consider enabling GitHub pages for the docs folder, easier access.

**Comment by UnsignedArduino** [comment]
I'm 4 parallel universes ahead of you lol:
https://unsignedarduino.github.io/TkZero/

**Comment by Bobingstern** [comment]
I meant that you should put it in the readMe but ok

**Comment by UnsignedArduino** [comment]
You mean to put a link to the documentation in the README? Because I'll fix up the README after I get the CI pipeline working 👍

**Comment by Bobingstern** [comment]
Yes, at the moment it's pretty bland. I'll make a fork and change some things
